# Generated by Django 3.0.8 on 2021-04-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=15)),
                ('request_timestamp', models.DateTimeField(db_index=True)),
                ('response_time', models.BigIntegerField()),
            ],
        ),
    ]
